### ISSUE TITLE
Can't see a domain that I created as a Convergence user with the "Developer" role

### ISSUE THREAD

**Issue by alalonde** [convergencelabs/convergence-project#93]
To reproduce:

1. In the admin console, create a new convergence user with the "Developer role"
2. Log out
3. Log back in with the new user
4. Create a domain

There is no visual feedback that the domain is being created, but no error either.

**Comment by mmacfadden** [comment]
<@alalonde> I think this has been fixed. I pushed some code, can you test?

**Comment by alalonde** [comment]
Pulled the server and admin console and tried again. Still seeing the same behavior.

**Comment by alalonde** [comment]
When I log out and back in as the `admin` superuser I can see the domain. But not as a `developer`

**Comment by mmacfadden** [comment]
Ahh.  There was another bug in the same file.  Just pushed another commit.  Should be fixed now.

**Comment by alalonde** [comment]
OK that seems to have fixed it. Thanks!
